#!/bin/sh
cd /var/www/mvp
git pull origin master
source /var/www/mvp/.venv/bin/activate
pip3 install -r requirements.txt
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py collectstatic --noinput
sudo service apache2 restart