name: Django Demo CI

on:
  push:
    branches: [ staging, github-ci, sit-new, deploy, feature*, fix*, feature_*-run, fix_*-run, feature-*-run, fix-*-run]

  pull_request:
      branches: [ master, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies, run migrations
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#        pip install pytest-django
    - name: Run migrations
      run: |
        python config/manage.py makemigrations
        python config/manage.py migrate
    - name: Run tests
      # ... your test step here
      #run: python config/manage.py test apps common --parallel=4 --failfast
#    - name: Slack Notification
#      uses: rtCamp/action-slack-notify@v2.0.2
#      env:
#        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

